steps:
  - label: 'Build and test :hammer:'
    command:
      - .buildkite/build-and-test.sh

  - label: 'Deploy to dev (sharonohk) :shipit:'
#    branches: master
    command:
      - .buildkite/deploy.sh